...
INSTALLED_APPS = (
    ...
    'rest_framework_simplejwt.token_blacklist',
    ...
)
...
...
SIMPLE_JWT = {
  'ACCES_TOKEN_LIFETIME' : datetime.timedelta(minutes = 5)
  'REFRESH_TOKEN_LIFETIME' : datetime.timedelta(days = 1)
}
...
...
